services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prm-app-prod
    restart: unless-stopped
    ports:
      - "3456:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      RUN_MIGRATIONS: "false"
      RUN_SEED: "false"
